// PWA Service Worker - Generated by it.adi.p Automator V6
const CACHE_NAME = "app-v9-clean";
const ASSETS = ["./","./index.html","./manifest.json"];
self.addEventListener('install', event => {
  self.skipWaiting();
});

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys().then(keys =>
      Promise.all(keys.map(key => caches.delete(key)))
    )
  );
  self.clients.claim();
});
