// PWA Service Worker - Generated by it.adi.p Automator V6
const CACHE_NAME = 'cetak_struk-cache-v1777284878375';
const ASSETS = ["./","./index.html","./manifest.json"];
self.addEventListener('install', (event) => {
    self.skipWaiting();
    event.waitUntil(caches.open(CACHE_NAME).then((cache) => cache.addAll(ASSETS)));
});
self.addEventListener('activate', (event) => {
    event.waitUntil(caches.keys().then((keys) => Promise.all(keys.map((k) => { if (k !== CACHE_NAME) return caches.delete(k); }))));
    return self.clients.claim();
});
self.addEventListener('fetch', (event) => {
    event.respondWith(fetch(event.request).catch(() => caches.match(event.request)));
});
